{% set version = '1.0-2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-hdci
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/HDCI_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/HDCI/HDCI_{{ version }}.tar.gz
  sha256: 7fb6f89df772fe8feb9e3e00e567600318b9ec16059c4c20acfef93549d9ab73

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-matrix
    - r-doparallel
    - r-foreach
    - r-glmnet
    - r-iterators
    - r-lattice
    - r-mvtnorm
    - r-slam
  run:
    - r-base
    - r-matrix
    - r-doparallel
    - r-foreach
    - r-glmnet
    - r-iterators
    - r-lattice
    - r-mvtnorm
    - r-slam

test:
  commands:
    - $R -e "library('HDCI')"           # [not win]
    - "\"%R%\" -e \"library('HDCI')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=HDCI
  license: GPL-2.0-only
  summary: Fits regression models on high dimensional data to estimate coefficients and use bootstrap
    method to obtain confidence intervals. Choices for regression models are Lasso,
    Lasso+OLS, Lasso partial ridge, Lasso+OLS partial ridge.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: HDCI
# Type: Package
# Title: High Dimensional Confidence Interval Based on Lasso and Bootstrap
# Version: 1.0-2
# Date: 2017-06-06
# Author: Hanzhong Liu, Xin Xu, Jingyi Jessica Li
# Maintainer: Xin Xu <xin.xu@yale.edu>
# Imports: glmnet, slam, parallel, foreach, iterators, doParallel, lattice, Matrix, mvtnorm
# Description: Fits regression models on high dimensional data to estimate coefficients and use bootstrap method to obtain confidence intervals. Choices for regression models are Lasso, Lasso+OLS, Lasso partial ridge, Lasso+OLS partial ridge.
# License: GNU General Public License version 2
# Repository: CRAN
# NeedsCompilation: no
# Packaged: 2017-06-06 18:45:06 UTC; xin
# RoxygenNote: 6.0.1
# Date/Publication: 2017-06-06 22:34:10 UTC
